### ISSUE TITLE
look into rule wording for website

### ISSUE THREAD

**Issue by kabobrocks** [redditdota2league/server#39]
"Captains are required to submit results from their matches to the Captain section of rd2l.com within 24 hours if the match was not ticketed. If matches cannot not ticketed due to an unforeseen issue, a screenshot of the score screen will suffice."

Needs to be reworded

**Comment by codeSkaterX** [comment]
This seems to be old section of rules still in from when rd2l.com was in use. It should be reworded to state that results should be submitted to the discord if needed or whatever the admins believe is best course of action (another option is to dm match result to division admin for instance).

For instance:

"Captains are required to message their division admin with the result of the match within 24 hours if the match was not ticketed. If matches cannot not ticketed due to an unforeseen issue, a screenshot of the score screen will suffice."

**Comment by kabobrocks** [comment]
updated, will go live on next push
